services:
  gatewayd:
    image: fedimint/gatewayd:v0.4.1
    command: gatewayd lnd
    environment:
      # Path to folder containing gateway config and data files
      - FM_GATEWAY_DATA_DIR=/gateway_data
      # Gateway webserver listen address
      - FM_GATEWAY_LISTEN_ADDR=0.0.0.0:8175
      # Public URL from which the webserver API is reachable
      - FM_GATEWAY_API_ADDR=${FM_GATEWAY_API_ADDR}
      # Gateway webserver authentication password
      - FM_GATEWAY_PASSWORD=${FM_GATEWAY_PASSWORD}
      # Configured gateway routing fees Format: <base_msat>,<proportional_millionths>
      - FM_GATEWAY_FEES=0,10000
      # LND RPC address
      - FM_LND_RPC_ADDR=${FM_LND_RPC_ADDR}
      # LND TLS cert file path
      - FM_LND_TLS_CERT=${FM_LND_TLS_CERT}
      # LND macaroon file path
      - FM_LND_MACAROON=${FM_LND_MACAROON}
    volumes:
      - gateway_datadir:/gateway_data
    ports:
      - "8175:8175"
      - "8080:8080"
    depends_on:
      - lnd
    restart: always
    platform: linux/amd64

  gateway-ui:
    image: fedimintui/gateway-ui:0.4.2
    # image: gateway-ui
    ports:
      - "0.0.0.0:3001:3001"
    environment:
      - PORT=3001
      - REACT_APP_FM_GATEWAY_API=http://127.0.0.1:8175
      - REACT_APP_FM_GATEWAY_PASSWORD=${FM_GATEWAY_PASSWORD}
    depends_on:
      - gatewayd
    restart: always
    platform: linux/amd64

volumes:
  gateway_datadir:
